version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "openapi-sam-test"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1dtj0lpbn2stg"
s3_prefix = "openapi-sam-test"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
